### ISSUE TITLE
415 status when submitting a single url

### ISSUE THREAD

**Issue by Ben-Steele** [seanthegeek/pyldfire#1]
When a single url is submitted using submit_urls a 415 status is always returned.  

example input: "https://www.google.com"
I've added a partial traceback, omitting full file paths. executed in python2.7.15
```
Traceback (most recent call last):
  File "myfile.py", line 43, in execute
    results = self.wildfire.submit_urls(self.url)
  File "pyldfire.py", line 221, in submit_urls
    response = self.session.post(request_url, data=data)
  File "requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "pyldfire.py", line 69, in _raise_errors
    raise WildFireException(WildFire._errors[response.status_code])
KeyError: 415
```

**Comment by seanthegeek** [comment]
Fixed in 9.0 release
