### ISSUE TITLE
Unsupported file type error when submitting multiple URLs

### ISSUE THREAD

**Issue by Ben-Steele** [seanthegeek/pyldfire#2]
When submitting multiple URLs with submit_urls, you always get an "Unsupport File type" error.

example inputs: `["https://www.google.com", "https://www.reddit.com"]`
I've added a partial traceback, omitting full file paths. executed in python2.7.15

```
Traceback (most recent call last):
  File "myfile.py", line 43, in execute
    results = self.wildfire.submit_urls(self.url)
  File "pyldfire.py", line 214, in submit_urls
    response = self.session.post(request_url, data=data, files=files)
  File "requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "pyldfire.py", line 67, in _raise_errors
    raise WildFireException(results["error"]["error-message"])
pyldfire.WildFireException: 'Unsupport File type With submit links'
```

**Comment by seanthegeek** [comment]
Fixed in 9.0 release
